### ISSUE TITLE
[BONTY] Thirst and Hunger $30+

### ISSUE THREAD

**Issue by MosleyTheMalO** [SPLURT-Station/S.P.L.U.R.T-tg#24]
Port over the thirst system from our current codebase, and also add the thirst and hunger icons that our current codebase has
The system should be functional, serve the same purpose as in our original codebase, and not cause issues with the systems set in place in this codebase
 
- [x] Port of thirst
- [ ] Thirst and Hunger status icons

The bounty price set is only the base amount we offer, we can discuss payment to offer you more money than what stated.

**Comment by omarsoufiane** [comment]
@MosleyTheMalO Hello, I noticed this issue has been completed but it's still unclaimed in bountyhub, you can retract you bounty or ask Krashly to claim it there
